spring:
  application:
    name: springboot-graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-hotel
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
